parameters:
  host: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.host }}
  pool: ${{ parameters.pool }}
  steps:
  - ${{ if eq(parameters.host, 'Windows') }}:
    - script: 'npm install -g esy@latest --unsafe-perm'
      displayName: 'Install esy'
  - ${{ if ne(parameters.host, 'Windows') }}:
    - script: 'sudo npm install -g esy@latest --unsafe-perm'
      displayName: 'Install esy'
  - script: esy
    displayName: 'esy'
